name: ayb_database
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  adobe_xd: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  url_launcher: ^6.1.8
  cached_network_image: ^3.2.3
  firebase_auth: ^4.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/ayb_logo.png
    - assets/images/street.jpg
    - assets/images/google_logo.png
    - assets/images/events_pics/AYB_Group_Photo.jpg
    - assets/images/events_pics/KNOCK_ON_DOOR.jpg
    - assets/images/events_pics/R&D.jpg
    - assets/images/charity.jpg
    - assets/images/YDP2.png
    - assets/images/YDP.jpg
    - assets/images/PR.png
    - assets/images/hr.png
    - assets/images/donation.jpg
    - assets/images/MM.jpg
    - assets/images/social_media/facebook.png
    - assets/images/social_media/instagram.png
    - assets/images/2010/first_pic.jpg
    - assets/images/2010/masjed.jpg
    - assets/images/2014/qafla2014.jpg
    - assets/images/2014/btateen2014.jpg
    - assets/images/2014/ramadan2014.jpg
    - assets/images/2016/keswa2016.jpg
    - assets/images/2016/keswa2016(1).jpg
    - assets/images/2016/keswa2016(2).jpg
    - assets/images/2017/pyramids.jpg
    - assets/images/2017/pyramids(1).jpg
    - assets/images/2017/ramadan2017.jpg
    - assets/images/2019/kiss.jpg
    - assets/images/2019/packing.jpg
    - assets/images/2019/qafla.jpg
    - assets/images/donation/vodafone.png
    - assets/images/donation/telda.png
    - assets/images/donation/cash.png
    - assets/images/groupPhoto.jpg
    - assets/images/shapes/shape1.png
    - assets/images/shapes/shape2.png
    - assets/images/shapes/shape3.png
    - assets/images/shapes/shape4.png
    - assets/images/shapes/shape5.png
    - assets/images/shapes/shape6.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/debt.png"